server:
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: SPRING_DATASOURCE_URL
    username: root
    password: SPRING_DATASOURCE_PASSWORD

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : create # validate ? ????